[General]
TcpServerPort = 5790
ReportStats = false
MavlinkDialect = ardupilotmega

[TcpEndpoint sitl]
Address = 127.0.0.1
Port = 5760
RetryTimeout = 5

[UdpEndpoint qgc]
Mode = Normal
Address = 192.168.65.254
Port = 14550

[UdpEndpoint camera_sensor]
Mode = Normal
Address = 172.20.0.3
Port = 14551