[General]
TcpServerPort = 5790
ReportStats = false
MavlinkDialect = ardupilotmega

[TcpEndpoint sitl]
Address = 127.0.0.1
Port = 5760
RetryTimeout = 5

[UdpEndpoint qgc]
Mode = Normal
Address = host.docker.internal
Port = 14550

